name: deploy python package

on:
  push:
    tags:
      - '*'

jobs:
  build_wheel:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]

    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode version
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_SKIP: "*-musllinux* pp*"
          MACOSX_DEPLOYMENT_TARGET: 11.00
          CIBW_BUILD_VERBOSITY: 2

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{matrix.os}}
          path: ./wheelhouse/*.whl


  upload_pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheel]
    environment:
      name: pypi
      url: https://pypi.org/p/trianglelite
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
